### ISSUE TITLE
Wrong tutorial as a start tutorial!

### ISSUE THREAD

**Issue by Sandybig** [grafana/tutorials#101]
This was one of the worst courses/tutorials/intros that I have come across of many decades in IT!
Do not put developers in front of a newby audience - they are not good at that sort of thing.

**Comment by marcusolsson** [comment]
Thank you for your feedback. We're constantly working on improving our documentation and resources for learning Grafana, and I'd very much like to improve the experience you had.

 I assume that you're referring to the tutorial called "Grafana Fundamentals"? It would be helpful to me if you could point me to where the tutorial is too demanding of newcomers. I'd also be happy to answer any questions that you feel the tutorial failed to provide.

**Comment by Sandybig** [comment]
Hi,

Yes the FIRST introduction to Grafana.

My point was not that newbies to Grafana would find it too demanding.

My point is that so much time is spent (in my opinion, needlessly) on a lot of things that were not an intro to Grafana.

Not valuable in an intro:
- 30 mins download Docker. Not part of an INTRO & heavy on download & time.
- Using other systems at part of intro - 10 mins in to the ‘tutorial’ before you actually get to Grafana.
- A very limited Use Case underlying the tutorial.
- No real setting out what you are trying to achieve & what the underlying data is.
- In short most of this is someone’s own experience & goals not a thought about the end recipients needs.

What did I learn about Grafana in the time - not a lot!

An INTRO is just that, an Introduction - all about the topic being introduced & should be immediate, tactile & focused on the topic.

I think Grafana looks really good but this sort of thing nearly put me off.

Don’t put developers / techies on such things - years of examples of why that is not the clever way to go.

Regards, Sandy Riach
+44 7955 889 767
s/y Cisco II, Ionian Sea, Greece
“Stay positive, Test negative!“

On 26 Jan 2021, at 16:30, Marcus Olsson <notifications@github.com> wrote:

﻿

Thank you for your feedback. We're constantly working on improving our documentation and resources for learning Grafana, and I'd very much like to improve the experience you had.

I assume that you're referring to the tutorial called "Grafana Fundamentals"? It would be helpful to me if you could point me to where the tutorial is too demanding of newcomers. I'd also be happy to answer any questions that you feel the tutorial failed to provide.

**Comment by marcusolsson** [comment]
Thank you for taking the time to get back to me, and for clarifying things for me.

Grafana (simplified) is a visualization tool that, unfortunately, doesn't accomplish much on its own. For this reason, we believe that adding data sources should be part of a tutorial that teaches the fundamentals of Grafana. What that in mind, I'll do my best to address your feedback:

- Requiring Docker is indeed an obstacle. We chose to use Docker here instead of asking the reader to install and configure the data sources themselves. As you said, the tutorial should focus on Grafana and we don't want to spend time on installing a data source that the reader won't be using anyway after the tutorial is over.
- By "limited use case", are you referring to monitoring a web service? As monitoring web services is one of the most common use cases of Grafana, we think that many users (not all unfortunately) will be able to relate. 
- You felt that the tutorial didn't do a good job of explaining what you'll achieve by the end of it, is valuable feedback indeed. We'll have a look at clarifying this better.

That being said, explaining why we've written the tutorial in this way, won't change the fact that you ultimately didn't feel it was relevant to where you are. Would it have been helpful to have an initial guide/tutorial, that don't make use of any data sources, where you'd get to familiarize yourself with the UI before diving into the fundamentals tutorial?

**Comment by Sandybig** [comment]
Hi,

Thanks for the rational/opinions.

It is what it is I suppose. Sales and Marketing may not be happy with a limited view of applicability.

You could publish a data source (simple data) and have people connect to it THEN focus on how to set up a dashboard to show that data in basic (then more sophisticated if possible). Value would be immediate details of how to best set up a set of dashboard screens (low key best practice). This would get people able to use it with confidence. Then perhaps Docker for multiple, more sophisticated views of how it could be used but even then I would question the Docker bit. [btw I use Docker on other systems and find it valuable, just not on my personal Mac]

Always a good idea to have a clear view of what your reason is for doing the tutorial, what your audience is, what they might want, what your marketing message is. Then make it clear at the start and show at the end show what should have been achieved. This presented in a simple overview of the learning trajectory(s) being presented.

Regards, Sandy

Sandy Riach
sandy@riach.com
mobile (UK):   +44 7955 889 767
mobile (Gr): +30 698 703 9513
s/y Cisco II, Ionian Sea, Greece
["Stay Positive, Test Negative"]
_______________________________________________________________________________________________________________________
PRIVACY AND CONFIDENTIALITY NOTICE
This email, and any files transmitted with it, is strictly confidential and intended solely for the person or
organisation to whom it is addressed. If it comes to the attention of any other unauthorised person, no action may
be taken on it nor should it be copied or shown to any third party. This email message has been swept for the presence
of computer viruses. If you have received this email in error please return it to mailto:postmaster@riach.com
_______________________________________________________________________________________________________________________

**Comment by matthewhelmke** [comment]
Closing. Feedback has been taken to heart.
